In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("CUSTOMER BEHAVIOUR.CSV.CSV")

In [3]:
df.head(20)

,Customer ID,Age,Gender,Item Purchased,CategoryPurchase,Amount (INR),Location,Size,Color,SeasonReview,Rating,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,CUST0001,58,Male,Blouse,Outerwear,4262,Hyderabad,L,White,Winter,Very Good,3.3,Yes,Free Shipping,Yes,14,Bank Transfer,Annually
1,CUST0002,19,Other,Sandals,Accessories,3861,Ahmedabad,11,Green,Winter,Good,4.1,No,Express,Yes,13,PayPal,Weekly
2,CUST0003,23,Female,Sweater,Outerwear,14135,Kolkata,11,Green,Winter,Poor,3.6,No,Free Shipping,No,40,Bank Transfer,Monthly
3,CUST0004,54,Male,Shorts,Clothing,1000,Hyderabad,XXL,White,Spring,Excellent,3.1,No,Express,Yes,23,PayPal,Fortnightly
4,CUST0005,60,Female,Shorts,Clothing,10230,Bangalore,10,Red,Spring,Poor,3.1,Yes,Express,Yes,14,Credit Card,Monthly
5,CUST0006,43,Female,Sweater,Footwear,9542,Kolkata,XL,Purple,Fall,Poor,2.4,Yes,Standard,No,47,Bank Transfer,Quarterly
6,CUST0007,55,Female,Shirt,Footwear,2516,Jaipur,9,White,Winter,Excellent,2.5,Yes,Next Day Air,Yes,24,Cash on Delivery,Annually
7,CUST0008,47,Other,Sneakers,Clothing,11395,Delhi,10,Green,Summer,Excellent,2.9,Yes,Next Day Air,Yes,46,UPI,Monthly
8,CUST0009,50,Male,Dress,Clothing,14512,Chennai,10,Grey,Spring,Good,3.1,Yes,Store Pickup,Yes,38,PayPal,Quarterly
9,CUST0010,19,Male,Shirt,Outerwear,4173,Mumbai,XL,Grey,Winter,Excellent,4.2,Yes,Store Pickup,Yes,8,UPI,Quarterly
10,CUST0011,53,Male,Sneakers,Accessories,3720,Jaipur,XL,Green,Fall,Average,3.3,No,Free Shipping,Yes,14,Credit Card,Monthly
11,CUST0012,19,Other,Dress,Footwear,9891,Hyderabad,S,White,Winter,Good,2.2,Yes,Express,Yes,32,Debit Card,Monthly
12,CUST0013,60,Female,Sandals,Footwear,12101,Lucknow,11,Purple,Spring,Poor,4.4,Yes,Free Shipping,Yes,42,Cash on Delivery,Monthly
13,CUST0014,45,Female,T-shirt,Clothing,11282,Delhi,S,Pink,Summer,Excellent,2.7,Yes,Store Pickup,No,8,Cash on Delivery,Fortnightly
14,CUST0015,35,Female,Sandals,Clothing,7510,Jaipur,M,Black,Winter,Excellent,4.8,Yes,Standard,No,31,Cash on Delivery,Fortnightly
15,CUST0016,43,Male,Jeans,Accessories,285,Pune,XXL,Purple,Summer,Poor,4.1,No,Standard,Yes,18,Debit Card,Weekly
16,CUST0017,55,Other,Dress,Clothing,12504,Kolkata,S,Black,Fall,Very Good,4.8,Yes,Free Shipping,Yes,11,Credit Card,Annually
17,CUST0018,22,Other,Sandals,Accessories,2214,Lucknow,XL,Grey,Winter,Very Good,2.2,No,Express,Yes,42,UPI,Monthly
18,CUST0019,33,Female,Jacket,Footwear,11254,Chennai,9,Yellow,Winter,Excellent,3.4,Yes,Free Shipping,Yes,32,PayPal,Fortnightly
19,CUST0020,40,Male,Sandals,Outerwear,4919,Bangalore,9,Brown,Summer,Very Good,5.0,Yes,Store Pickup,No,42,Credit Card,Fortnightly

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             1000 non-null   str
 1   Age                     1000 non-null   int64
 2   Gender                  1000 non-null   str
 3   Item Purchased          1000 non-null   str
 4   CategoryPurchase        1000 non-null   str
 5   Amount (INR)            1000 non-null   int64
 6   Location                1000 non-null   str
 7   Size                    1000 non-null   str
 8   Color                   1000 non-null   str
 9   SeasonReview            1000 non-null   str
 10  Rating                  1000 non-null   str
 11  Review Rating           1000 non-null   float64
 12  Subscription Status     1000 non-null   str
 13  Shipping Type           1000 non-null   str
 14  Discount Applied        1000 non-null   str
 15  Previous Purchases      1000 non-null   int64
 16  Payment Method          1000 non-null   str
 17  Frequency of Purchases  1000 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 140.8 KB

In [5]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,CategoryPurchase,Amount (INR),Location,Size,Color,SeasonReview,Rating,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,1000,1000.0000,1000,1000,1000,1000.000000,1000,1000,1000,1000,1000,1000.000000,1000,1000,1000,1000.000000,1000,1000
unique,1000,NaN,3,13,4,NaN,10,10,10,4,5,NaN,2,5,2,NaN,6,5
top,CUST0001,NaN,Other,Sweater,Footwear,NaN,Ahmedabad,XL,Grey,Winter,Excellent,NaN,No,Next Day Air,Yes,NaN,Credit Card,Monthly
freq,1,NaN,350,88,259,NaN,111,116,113,261,224,NaN,518,217,514,NaN,180,216
mean,NaN,43.7040,NaN,NaN,NaN,7365.714000,NaN,NaN,NaN,NaN,NaN,3.493200,NaN,NaN,NaN,25.033000,NaN,NaN
std,NaN,14.9072,NaN,NaN,NaN,4250.785601,NaN,NaN,NaN,NaN,NaN,0.850292,NaN,NaN,NaN,14.619975,NaN,NaN
min,NaN,18.0000,NaN,NaN,NaN,267.000000,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,0.000000,NaN,NaN
25%,NaN,31.0000,NaN,NaN,NaN,3638.500000,NaN,NaN,NaN,NaN,NaN,2.800000,NaN,NaN,NaN,13.000000,NaN,NaN
50%,NaN,45.0000,NaN,NaN,NaN,7206.500000,NaN,NaN,NaN,NaN,NaN,3.500000,NaN,NaN,NaN,24.000000,NaN,NaN
75%,NaN,56.0000,NaN,NaN,NaN,10959.000000,NaN,NaN,NaN,NaN,NaN,4.200000,NaN,NaN,NaN,38.000000,NaN,NaN
max,NaN,70.0000,NaN,NaN,NaN,14993.000000,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
CategoryPurchase          0
Amount (INR)              0
Location                  0
Size                      0
Color                     0
SeasonReview              0
Rating                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [8]:
df = df.rename(columns={'amount_(inr)':'purchase_amount'})

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'categorypurchase',
       'purchase_amount', 'location', 'size', 'color', 'seasonreview',
       'rating', 'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='str')

In [10]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [11]:
df[['age','age_group']].head(10)

   age    age_group
0   58       Senior
1   19  Young Adult
2   23  Young Adult
3   54  Middle-aged
4   60       Senior
5   43        Adult
6   55  Middle-aged
7   47  Middle-aged
8   50  Middle-aged
9   19  Young Adult

In [12]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [13]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                      365               Annually
1                        7                 Weekly
2                       30                Monthly
3                       14            Fortnightly
4                       30                Monthly
5                       90              Quarterly
6                      365               Annually
7                       30                Monthly
8                       90              Quarterly
9                       90              Quarterly

In [14]:
df = df.drop('rating', axis=1)

In [15]:
from sqlalchemy import create_engine

In [16]:
engine = create_engine(
    f"mysql+pymysql://{"root"}:{"yash74107410"}@{"localhost"}:{3306}/{"customer_behaviour"}"
)

In [17]:
table_name = "customer"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print("Data uploaded to MySQL successfully!")

Data uploaded to MySQL successfully!

In [18]:
result = pd.read_sql(
    "SELECT * FROM customer LIMIT 5;",
    engine
)

print(result)

  customer_id  age  gender item_purchased categorypurchase  purchase_amount  \
0    CUST0001   58    Male         Blouse        Outerwear             4262
1    CUST0002   19   Other        Sandals      Accessories             3861
2    CUST0003   23  Female        Sweater        Outerwear            14135
3    CUST0004   54    Male         Shorts         Clothing             1000
4    CUST0005   60  Female         Shorts         Clothing            10230

    location size  color seasonreview  review_rating subscription_status  \
0  Hyderabad    L  White       Winter            3.3                 Yes
1  Ahmedabad   11  Green       Winter            4.1                  No
2    Kolkata   11  Green       Winter            3.6                  No
3  Hyderabad  XXL  White       Spring            3.1                  No
4  Bangalore   10    Red       Spring            3.1                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0  Free Shipping              Yes                  14  Bank Transfer
1        Express              Yes                  13         PayPal
2  Free Shipping               No                  40  Bank Transfer
3        Express              Yes                  23         PayPal
4        Express              Yes                  14    Credit Card

  frequency_of_purchases    age_group  purchase_frequency_days
0               Annually       Senior                      365
1                 Weekly  Young Adult                        7
2                Monthly  Young Adult                       30
3            Fortnightly  Middle-aged                       14
4                Monthly       Senior                       30

In [19]:
df.to_sql(
    'customer',
    con=engine,
    if_exists='replace',
    index=False
)

1000